"""Entity-type inference jobs in the database instead of process memory.

The jobs were a module-level dict, which works only in a single process. This
deployment runs UVICORN_WORKERS=4: the POST that starts a job lands on one
worker, the status polls are load-balanced across all four, and roughly three
polls in four answered "Job not found" for a job that existed — just not in the
worker that was asked.

Revision ID: etjob001
Revises: ingest002
Create Date: 2026-08-31
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'etjob001'
down_revision = 'ingest002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        'entity_type_inference_job',
        # uuid4().hex, generated by the service so the POST can return the id
        # without a round trip.
        sa.Column('job_id', sa.String(length=32), nullable=False),
        sa.Column('silo_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        # The whole job dict, returned to the UI as-is. JSONB rather than a
        # column per field: the fields are progressive and open-ended (status,
        # done, total, sampled, types, candidates, error) and the row is deleted
        # minutes later, so mirroring each one would mean a migration every time
        # the inference gains a phase.
        sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint('job_id'),
        # CASCADE: a job is scratch state about one silo and must not outlive it.
        sa.ForeignKeyConstraint(
            ['silo_id'], ['Silo.silo_id'],
            name='fk_entity_type_inference_job_silo', ondelete='CASCADE',
        ),
    )
    # silo_id: the router checks it so a job id cannot be polled from another
    # silo. created_at: the only non-key query is the expiry sweep by age.
    op.create_index(
        'ix_entity_type_inference_job_silo_id',
        'entity_type_inference_job', ['silo_id'],
    )
    op.create_index(
        'ix_entity_type_inference_job_created_at',
        'entity_type_inference_job', ['created_at'],
    )


def downgrade() -> None:
    # No data to preserve: rows are transient job state, expired after an hour
    # by the service itself. Dropping the table only means any in-flight
    # inference has to be re-run, which is a button press.
    op.drop_index(
        'ix_entity_type_inference_job_created_at',
        table_name='entity_type_inference_job',
    )
    op.drop_index(
        'ix_entity_type_inference_job_silo_id',
        table_name='entity_type_inference_job',
    )
    op.drop_table('entity_type_inference_job')
