"""EntityTypeInferenceJob — progress/result of one entity-type inference run.

In the database rather than in process memory because the backend runs several
uvicorn workers (UVICORN_WORKERS=4 in this deployment). The POST that starts a
job lands on one worker, the status polls are load-balanced across all of them,
and a per-process dict meant roughly three polls in four answered "Job not
found" — the job existed, just not in the worker that was asked.

Rows are disposable: a job lasts a couple of minutes and is expired by
``EntityTypeInferenceService`` once the UI has had time to read the result. The
table exists to be *shared between processes*, not to keep history.
"""

from datetime import datetime

from sqlalchemy import JSON, Column, DateTime, ForeignKey, Integer, String
from sqlalchemy.dialects.postgresql import JSONB

from db.database import Base


class EntityTypeInferenceJob(Base):
    __tablename__ = "entity_type_inference_job"

    # uuid4().hex — 32 chars, generated by the service, not the database, so the
    # POST can return it without a round trip.
    job_id = Column(String(32), primary_key=True)

    # Scoped so a job id cannot be polled from another silo (the router checks
    # it), and so deleting a silo takes its jobs with it.
    silo_id = Column(
        Integer, ForeignKey("Silo.silo_id", ondelete="CASCADE"),
        nullable=False, index=True,
    )

    # Indexed: the only non-key query is the expiry sweep by age.
    created_at = Column(
        DateTime, nullable=False, default=datetime.utcnow, index=True,
    )

    # The whole job dict, returned to the UI as-is. A JSON blob rather than a
    # column per field because the fields are progressive and open-ended
    # (status, done, total, sampled, types, candidates, error) — mirroring each
    # one would mean a migration every time the inference gains a phase, for
    # state that is deleted minutes later.
    #
    # JSONB on Postgres (what the migration creates), plain JSON elsewhere:
    # bare JSONB cannot be compiled by other dialects at all, which made the
    # table impossible to create in a SQLite unit test.
    payload = Column(JSON().with_variant(JSONB, "postgresql"), nullable=False)
